name: Java App Build & Deployment Pipeline

on:
  push:
    branches:
      - kubespray

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 729691315449.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPOSITORY: java-app-img
  EKS_CLUSTER: java-app-cluster
  IMAGE_TAG: $GITHUB_SHA

jobs:
  build-and-push:
    name: build & push java app docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      - name: build & push java app docker image
        id: build-image
        run: |
          docker buildx build --platform linux/amd64 \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --push .

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{EKS_CLUSTER}} --region ${{env.AWS_REGION}}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/java-app java-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl apply -f k8s/
